name: Devio Activity

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-activity:
    name: DevIO Activity
    runs-on: ubuntu-latest
    steps:
      - uses: bun913/devio-activity@main
        with:
          AUTHOR_ID: "bun913"
          # 以下オプション
          # GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
